gateway:
  replicaCount: 1
  dataplaneNamespace: opensandbox
  providerType: batchsandbox
  gatewayRouteMode: header
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  secureAccess:
    existingSecret: opensandbox-secure-access
  service:
    type: ClusterIP
    port: 80
