apiVersion: v1
kind: Service
metadata:
  name: opensandbox-server-internal
  namespace: opensandbox-system
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: opensandbox-server
    app.kubernetes.io/instance: opensandbox-server
---
apiVersion: v1
kind: Service
metadata:
  name: opensandbox-ingress-gateway-internal
  namespace: opensandbox-system
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 28888
      protocol: TCP
  selector:
    app.kubernetes.io/name: opensandbox-ingress-gateway
    app.kubernetes.io/instance: opensandbox-ingress
