server:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  service:
    type: ClusterIP
  env:
    - name: OPENSANDBOX_SERVER_API_KEY
      valueFrom:
        secretKeyRef:
          name: opensandbox-runtime-secrets
          key: api-key
  gateway:
    enabled: true
    host: "127.0.0.1"
    gatewayRouteMode: header
    secureAccess:
      activeKey: a
      existingSecret: opensandbox-secure-access
  volumeMounts:
    - name: aks-kata-template
      mountPath: /etc/opensandbox/aks-kata.batchsandbox-template.yaml
      subPath: batchsandbox-template.yaml
      readOnly: true
  volumes:
    - name: aks-kata-template
      configMap:
        name: aks-kata-batchsandbox-template

configToml: |
  [server]
  host = "0.0.0.0"
  port = 80
  api_key = ""
  max_sandbox_timeout_seconds = 3600

  [log]
  level = "INFO"

  [runtime]
  type = "kubernetes"
  execd_image = "sandbox-registry.cn-zhangjiakou.cr.aliyuncs.com/opensandbox/execd:v1.1.0"

  [storage]
  allowed_host_paths = []
  volume_default_size = "1Gi"

  [kubernetes]
  kubeconfig_path = ""
  namespace = "opensandbox"
  informer_resync_seconds = 300
  informer_watch_timeout_seconds = 60
  sandbox_create_timeout_seconds = 120
  workload_provider = "batchsandbox"
  image_pull_policy = "IfNotPresent"
  batchsandbox_template_file = "/etc/opensandbox/aks-kata.batchsandbox-template.yaml"

  [egress]
  image = "sandbox-registry.cn-zhangjiakou.cr.aliyuncs.com/opensandbox/egress:v1.1.7"
  mode = "dns+nft"
  disable_ipv6 = true

  [secure_runtime]
  type = "kata"
  k8s_runtime_class = "kata-vm-isolation"
